pyth-network/pyth-gitbook

- README.md
- SUMMARY.md
- consumers/aptos.md
- consumers/best-practices.md
- consumers/consume-data.md
- consumers/evm.md
I'm taking a pass through our documentation in prep for our crosschain launch.
> Doc updates part 1

- consumers/best-practices.md
ran the text by compliance as well
> Add section on fees

- SUMMARY.md
- consumers/best-practices.md
- consumers/consume-data.md
- consumers/on-demand.md
- consumers/why-on-demand.md
Wrote a discussion of the on-demand update model with pros/cons for developers. Feedback appreciated!
> Why on demand

- consumers/best-practices.md
i already ran this by nagel for a legal review.
> Latency section

- consumers/best-practices.md
- consumers/solana.md
Tried to clarify the latency section text a bit, and added a link to the solana example.
> Minor gitbook edits

- consumers/aptos.md
- consumers/evm.md
- consumers/terra.md
- update aptos and evm price feed ids urls
- remove terra price feed ids reference
> update price feed ids urls

- consumers/on-demand.md
add a connection form the adversarial selection portion to the latency best practices
> Pointer to latency docs

- consumers/evm.md
> Remove ropsten network

- .gitignore
- SUMMARY.md
- consumers/on-demand.md
- how-pyth-works/design-overview.md
- how-pyth-works/pythnet.md
also some links to that description
> Add description of Pythnet to docs

- how-pyth-works/cross-chain.md
- pythnet link
- descrip for img
> additional cross chain changes

- publishers/pyth-client-websocket-api.md
We have agreed that this is how we will proceed going forward.
> Clarify stance on optional attr_dict fields

- pythnet-price-feeds/price-service.md
broken links for the price service
> [gitbook] update links

- pythnet-price-feeds/cross-chain-batches.md
On par with PR updates of the crosschain batches, replicated the batches here for the gitbook
> [gitbook] update docs to match with new batches

- pythnet-price-feeds/aptos.md
- pythnet-price-feeds/bas.md
- pythnet-price-feeds/cosmwasm.md
- fix aptos broken links
- fix bas broken links
- fix cosmwasm broken links
> fix aptos, bas, cosmwasm broken links

- pythnet-price-feeds/cross-chain-batches.md
removed the equity.br batches from Gitbook
> [gitbook] remove deleted batches

- pythnet-price-feeds/best-practices.md
- solana-price-feeds/best-practices.md
addition of the market hours section
including edits from feedback
> [gitbook] update market hours addition

- publishers/publish-data.md
- publishers/pyth-client-websocket-api.md
> update docs to point to pyth-agent

- metrics/kpi/february-23.md
small fix for feb23 apps integrations
requesting your review sirs
> revised feb'23 apps integrations

- README.md
add a 4th bullet point to redirect users to videos directly
and update 70 pubs to 80
> Add Tutorials Link to the Docs Intro

- solana-price-feeds/solana-price-feeds.md
add solana tutorial to solana price feeds section
> add solana tutorial to solana price feeds section

- pythnet-price-feeds/on-demand.md
add video to on demand section
> add video to on demand section

- pythnet-price-feeds/evm.md
add video link to the price pusher section
> add video link to the price pusher section

- pythnet-price-feeds/evm.md
it's currently in the middle of the "networks" section
> Fix position of example

- pythnet-price-feeds/best-practices.md
gm sirs
requesting your review to change FX and Metals hours from Sunday 5pm UTC to ET
> fix market hours for FX and Metals

- pythnet-price-feeds/aptos.md
- pythnet-price-feeds/cosmwasm.md
- pythnet-price-feeds/evm.md
- pythnet-price-feeds/sui.md
added links to contract - some missing but will update later on
some fixes for dead links
> Gitbook links
